name: EMILY Master Shopify Sync
on:
  schedule:
    - cron: '0 * * * *' # Constant background sync
  workflow_dispatch: # Manual trigger

env:
  SHOPIFY_STORE_URL: 'miraclespritz.net'
  SHOPIFY_API_VERSION: '2026-01'
  # Explicitly defining full scopes for Orders, SEO, and Inventory
  FULL_SCOPES: 'read_orders,write_orders,read_products,write_products,read_inventory,write_inventory,read_content,write_content'

jobs:
  shopify_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Execute Full-Access Sync
        run: |
          echo "Initiating EMILY Master Protocol for miraclespritz.net..."
          
          # Pulling the real sales data you need right now
          curl -X GET "https://${{ env.SHOPIFY_STORE_URL }}/admin/api/${{ env.SHOPIFY_API_VERSION }}/orders.json?status=any&limit=50" \
          -H "X-Shopify-Access-Token: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}" > latest_orders.json
          
          # Auditing the pH 4.6 formula inventory and SEO tags
          curl -X GET "https://${{ env.SHOPIFY_STORE_URL }}/admin/api/${{ env.SHOPIFY_API_VERSION }}/products.json" \
          -H "X-Shopify-Access-Token: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}" > product_audit.json

      - name: Log Data to GEO1 Bridge
        run: |
          git config --global user.name "EMILY-Bot"
          git config --global user.email "emily@amplifyaccessibility.org"
          git add latest_orders.json product_audit.json
          git commit -m "EMILY: Verified Sync - miraclespritz.net [$(date)]" || echo "No changes"
          git push
