name: G1 PRODUCTION MASTER SYNC
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  production_sync:
    runs-on: ubuntu-latest
    steps:
      - name: G1 Auth Handshake
        run: |
          echo "Authorizing G1 Master Node: 181014607001"
          # Using the GEO_ID for project context
          gcloud config set project emilyseo

      - name: Pull Shopify Orders (Production)
        run: |
          # Pulling the real data from miraclespritz.net
          curl -X GET "https://miraclespritz.net/admin/api/2026-01/orders.json?status=any" \
          -H "X-Shopify-Access-Token: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}" > production_orders.json

      - name: Log to G1 Dashboard
        run: |
          git config --global user.name "EMILY-G1-Bot"
          git add production_orders.json
          git commit -m "G1: Production Sales Audit [$(date)]" || echo "No new sales"
          git push
