name: Shopify Theme Sync

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'index.html'
      - 'index.js'

jobs:
  deploy:
    name: Sync to Shopify Store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Shopify Theme CLI
        uses: shopify/theme-action@v3
        with:
          shopify_store_url: ${{ secrets.SHOPIFY_STORE_URL }}
          shopify_password: ${{ secrets.SHOPIFY_PASSWORD }}
          theme_id: ${{ secrets.SHOPIFY_THEME_ID }}
          path: ./
          allow_live: true

      - name: Post-Sync Notification
        run: echo "Deployment to Shopify complete. Terminal synced."
