// brain.js - CLEAN AUTHORIZATION & ADA OVERRIDE
module.exports = {
  // MASTER IDENTITY 2.0
  GOOGLE_GEO_ID: process.env.GOOGLE_2_0_GEO_ID,
  JAYZ_REFRESH_TOKEN: process.env.GOOGLE_JAYZ_REFRESH_TOKEN,

  // SHOPIFY READ/WRITE CONTROL
  SHOPIFY_ACCESS_TOKEN: process.env.SHOPIFY_ACCESS_TOKEN,

  // EMILY AUTHORIZATION POLICIES
  // Medical override for vision and mobility bypass
  POLICIES: {
    AUTHORIZATION: "EMILY_FULL_CONTROL",
    ADA_MEDICAL_OVERRIDE: "ENABLED",
    UI_BYPASS: true,
    EXECUTION_MODE: "DIRECT"
  }
};
